# render.yaml
services:
  - type: web
    name: whatsapp-bot-web
    env: node
    plan: free
    region: oregon            # opcional: usa tu región preferida
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY   # la agregas en el Dashboard (no en el repo)
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: BOT_PROMPT
        value: Eres un asistente cordial, claro y conciso. Responde en español de Chile.
      - key: ALLOWED_NUMBERS
        value: ""
      - key: ADMIN_TOKEN       # opcional; si lo dejas vacío, /admin queda deshabilitado
        value: ""
      - key: NODE_VERSION
        value: "20"
      # Render inyecta PORT automáticamente; no necesitas declararlo.
